### ISSUE TITLE
TA lib installs from pip but not from github setup.py, but from pip does have some error.. 

### ISSUE THREAD

**Issue by ntom** [mrjbq7/ta-lib#179]
Hi @mrjbq7 ,

Thanks for your work on this, I'm just reporting back on some errors / weird behaviour i noticed when trying to install ta-lib via the github repo and also when installing via pip.

I am running ubuntu 16.04 LTS on a x64 machine using pyenv.  

I have downloaded the ta-lib-0.4.0-src.tar.gz along with some `configure --prefix="/usr"... make.. sudo make install`...  no issues, nothing to report.   
   
Then i clone the github repo and `python3.6 setup.py install`   again... nothing to report, no errors. nothing.  
  
Then i test its installed `pip3.6 show ta-lib` .. reports back fine... version 0.4.16 etc location `/home/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages`  (as u can see i'm running pyenv.  
So everythings fine.

Then I go for a little check with `python3.6 -c "import talib"` .. now this is where I come across my first issue...  
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/username/Downloads/ta-lib-github/talib/__init__.py", line 4, in <module>
    from ._ta_lib import (
ModuleNotFoundError: No module named 'talib._ta_lib'
```
So I think to myself, hmm, thats odd, lets retry without using the github source code..   
So I remove it with `pip3.6 uninstall ta-lib` which reports back `Successfully uninstalled TA-Lib-0.4.16`.
I do a quick test with `pip3.6 show ta-lib`, and yeah, all done. Gone. 

-- 

So, i try reinstalling with the classic `pip3.6 install TA-Lib` ... here i get some more errors...

```python
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-yejoz3bc/TA-Lib/setup.py", line 130, in <module>
      install_requires = ['numpy'],
    File "/home/username/.pyenv/versions/3.6.4/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/username/.pyenv/versions/3.6.4/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/username/.pyenv/versions/3.6.4/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 213, in run
      archive_basename = self.get_archive_basename()
    File "/home/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 161, in get_archive_basename
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/home/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 155, in get_tag
      assert tag == supported_tags[0]
  AssertionError
  
  ----------------------------------------
  Failed building wheel for TA-Lib
  Running setup.py clean for TA-Lib
Failed to build TA-Lib
Installing collected packages: TA-Lib
  Running setup.py install for TA-Lib ... done
Successfully installed TA-Lib-0.4.16
```

Okay.. I got some weird ass error... but it did say it was installed.. again.. `pip3.6 show ta-lib` shows its installed, version 0.4.16.... lets test it on python... `python3.6 -c 'import talib'` and boom. It works.

So... some pretty weird ass strange behaviour...

**Comment by mrjbq7** [comment]
Hmm, yeah that ``install_requires = ["numpy"],`` line is a problem because it's a keyword that works in setuptools but not distutils.  Does your install work if you had ``setuptools`` installed beforehand?

Also, maybe I can find a better way to have distutils generate the "numpy required" manifest file.

**Comment by mrjbq7** [comment]
Maybe this helps?

258ef761f00dc8c5f5c38a4532fe2dded6c3de30

**Comment by mrjbq7** [comment]
Do you know if that change I made fixes it for you?

**Comment by ntom** [comment]
Hi @mrjbq7  - So yeah I wasn't looking forward to debugging this because i knew it was going to be a nightmare. .and since I had it installed and was working, I was happy. LOL... anyway, I took the plunge and completely removed all ta-lib, libta etc references off my box to  go 'clean' on this. 

**Here's what DOES work...**  - for the reference of others with this issue..  
1. Complete remove all `ta-lib` the python wrapper and `libta_lib` references.
```bash 
sudo pip3.6 uninstall ta-lib
sudo rm -rf /usr/lib/libta_lib.*
```
You can make sure everythings gone by checking with
```bash
sudo updatedb
locate talib
locate libta_lib
```
Check all the above references in your site-packages and /usr/lib or /usr/local/lib or wherever you installed are completely gone.   
   
2. Reinstall and make ta-lib
```bash
wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
cd ta-lib
./configure --prefix="/usr"
make
sudo make install
```
3. Install ta-lib
```bash  
sudo pip3.6 install ta-lib  
```
^ This works absolutely fine..  Output. . 
```
pip3.6 show ta-lib
```
```
Name: TA-Lib
Version: 0.4.16
Summary: Python wrapper for TA-Lib
Home-page: http://github.com/mrjbq7/ta-lib
Author: John Benediktsson
Author-email: mrjbq7@gmail.com
License: UNKNOWN
Location: /home/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages
Requires: numpy
```
```bash
python3.6 -c "import talib; print(talib.__ta_version__)"
```
```python
b'0.4.0 (Feb 13 2018 11:53:08)'
```

**And here, is what DOES NOT work... and the errors associated with it ...** 
1. Repeat step 1 above and completely remove all talib and libta_lib   
2. Repeat step 2 and reinstall and make ta-lib  
3. Install ta-lib python wrapper from github
```bash  
git clone https://github.com/mrjbq7/ta-lib.git talib-github   
cd talib-github   
sudo python3.6 setup.py install 
```
Check it's installed & output... 
```bash 
pip3.6 show ta-lib  
```  
```    
Name: TA-Lib
Version: 0.4.17
Summary: Python wrapper for TA-Lib
Home-page: http://github.com/mrjbq7/ta-lib
Author: John Benediktsson
Author-email: mrjbq7@gmail.com
License: UNKNOWN
Location: /home/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/TA_Lib-0.4.17-py3.6-linux-x86_64.egg
Requires: numpy
```  
^ Immediately i notice a change, before when installed with `pip` the location was just the `site-packages` directly but now seems to be a specific `.egg` file, idk if this would make a difference ?  
  
And then here we get the failure.. 
```bash  
python3.6 -c "import talib; print(talib.__ta_version__)"  
```  
```python   
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/username/Downloads/talib-github/talib/__init__.py", line 43, in <module>
    from ._ta_lib import (
ModuleNotFoundError: No module named 'talib._ta_lib'
```

**Comment by mrjbq7** [comment]
Wait, why is your error from ``/home/username/Downloads/talib-github/talib/__init__.py``.

Seems like you shouldn't be importing from the github download directory, but in a different directory since you want it to pull from ``/usr/local/lib/python3.6`` not ``~/Downloads/talib-github``.

**Comment by ntom** [comment]
> Wait, why is your error from /home/username/Downloads/talib-github/talib/__init__.py.    
  
I have no idea, I just followed the installation process and this is where it why trying to pull the file from when i installed using setup.py install vs say the pip3.6 install method.  
  
I did search 'pyenv .egg' and such a few times, i just did a quick google now and found this which could be relevant also [Pyenv shim not created when installing package using setup.py](https://stackoverflow.com/questions/29753592/pyenv-shim-not-created-when-installing-package-using-setup-py) but this is quite old going back to 2014 and my pyenv is very new/fresh  - `pyenv 1.2.1-6-g95ad305`  but still a possible issue there could be something todo with it as u said its passing the travis tests so...

**Comment by ntom** [comment]
Maybe we just close this issue call it a day, i mean we did good diagnosis and someone else may google and find it in the future and can reference it or build on it etc ?

**Comment by mrjbq7** [comment]
Sure, and I very much appreciate your help looking into problems!

**Comment by yorgee571** [comment]
因为我也遇到了，解决不了

**Comment by yorgee571** [comment]
#pip install TA-Lib
```
Collecting TA-Lib
  Using cached TA-Lib-0.4.16.tar.gz
Requirement already satisfied: numpy in ./anaconda3/lib/python3.6/site-packages (from TA-Lib)
Building wheels for collected packages: TA-Lib
  Running setup.py bdist_wheel for TA-Lib ... done
  Stored in directory: /home/yorgee/.cache/pip/wheels/61/db/65/9115f59e66acac52075c25b7059a7259d02f8c38d8709906b7
Successfully built TA-Lib
Installing collected packages: TA-Lib
Successfully installed TA-Lib-0.4.16
```
#python
`Python 3.6.3 |Anaconda custom (32-bit)| (default, Oct 13 2017, 14:21:34) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import talib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yorgee/anaconda3/lib/python3.6/site-packages/talib/__init__.py", line 4, in <module>
    from ._ta_lib import (
ModuleNotFoundError: No module named 'talib._ta_lib'`

**Comment by a5601564** [comment]
libta_lib.so.0: cannot open shared object file: No such file or directory

**Comment by a5601564** [comment]
this problem seem like to be death，

**Comment by mrjbq7** [comment]
I'm not sure what "seem like to be death" means.

However, your issue @a5601564 is unrelated.  Can't find ``libta_lib.so.0`` means it can't find the underlying ta-lib C library.  Did you make sure that was installed?

**Comment by mrjbq7** [comment]
I think many of these problems are related to not having the underlying ta-lib C library or trying to "run" ta-lib from within the source code directory causing python path to use that instead of the one you built and installed.

In any event, I released 0.4.17 which changes to use setuptools for installation if you have it which should hopefully fix a few small install issues.

The Travis CI has been working just fine for a long while.

**Comment by MaximusIndus** [comment]
I have tried my level best to identify...the issue... but it its a brick wall as soon as I start installing 0.4.17. 

My own suggestion - stop relying on others, build your own library - in Python. all the imports and refrences break the whole purpose of TA-Lib's existence and make it redundant + unreliable.

**Comment by bhavsarpratik** [comment]
Works on Ubuntu 18
```
wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
tar -xvf ta-lib-0.4.0-src.tar.gz
cd ta-lib
./configure --prefix=/usr
make
sudo make install
cd ..
rm -r ta-lib
pip install ta-lib
```

**Comment by paohuz** [comment]
> Works on Ubuntu 18
> 
> ```
> wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
> tar -xvf ta-lib-0.4.0-src.tar.gz
> cd ta-lib
> ./configure --prefix=/usr
> make
> sudo make install
> cd ..
> rm -r ta-lib
> pip install ta-lib
> ```

Still get this error
talib/_ta_lib.c:526:10: fatal error: ta-lib/ta_defs.h: No such file or directory

**Comment by mrjbq7** [comment]
@paohuz I'm sorry you're having problems, but when you say "still get this error", are you saying on Ubuntu 18?  On another OS?  

That message typically means that when you went to ``pip install ta-lib``, it wasn't able to find the TA-Lib C library that should have been installed prior as a dependency.

We look in specific directories for the library, perhaps you installed it somewhere else or forgot to ``make install`` which is required after building it.

https://github.com/mrjbq7/ta-lib/blob/master/setup.py#L36

**Comment by mrjbq7** [comment]
Could you try using the ``master`` branch to see if that works better for your installation?

**Comment by b4thesunrise** [comment]
@mrjbq7 @Shic1983 Notice this problem still leave unsolved, I also encounter the same problem:
`No module named 'talib._ta_lib'`
and after I
 `rm -rf ta-lib`
i.e. delete the folder downloaded from github, everything goes on well, I think it is just because we test the code in the same folder with the github code, and in that way the 
`from talib import _ta_lib`  
code will try to find _ta_lib in the github folder rather than the installed talib lib, a very simple explain and solution but since I found no clear answer to that question, I would like to make an add. Really thanks for this issue, helps me a lot in the problem solving process, also thanks for @bhavsarpratik code give me inspire to explain it.

**Comment by mrjbq7** [comment]
if you want to build ta-lib in-place and test in-place you can do that

$ make build

or

$ python3 setup.py build_ext --inplace

Then you can import from the local folder if thats what you're hoping to do.
